### ISSUE TITLE
No such file or directory - authconfig

### ISSUE THREAD

**Issue by erinn** [sous-chefs/sssd_ldap#38]
As of chef-client 14.2 and ssd_ldap 4.2.2 we are receiving the following errors, consistently across many hosts:
    Errno::ENOENT
    -------------
    No such file or directory - authconfig
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/sssd_ldap/recipes/default.rb
    
     70:   execute 'authconfig' do
     71:     command "authconfig #{node['sssd_ldap']['authconfig_params']}"
     72:     notifies :run, 'ruby_block[nsswitch sudoers]', :immediately
     73:     action :nothing
     74:   end
     75: end

Maybe a path issue? Maybe something else. 

### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
14.2

### Platform Details
RHEL 7.5

**Comment by tas50** [comment]
Ping @lamont-granquist
